### ISSUE TITLE
Remaining english words on french OS

### ISSUE THREAD

**Issue by pled** [GourmandRecipeManager/gourmand#46]
New recipe field's names are still in english, see below : 

![Capture d’écran de 2021-10-05 18-52-34](https://user-images.githubusercontent.com/2879483/136068319-dbad012e-7f04-4fe3-ba66-0b51e6dd7c6d.png)

### Steps to Reproduce
1. Open new recipe window
2. Look at field's names

### Expected Behavior
All names should be in french

### Environment
* Operating System: Ubuntu 20.04 FR
* Version or commit id: 1.0.0
* Installed as Flatpak or Python package?: Flatpak

**Comment by cydanil** [comment]
Thanks @pled!  
I'm a bit mystified as these fields are supposedly already translated, but it also occurs in other languages.  
I'll have a look.

**Comment by cydanil** [comment]
I figured what the issue was and resolved it:
![image](https://user-images.githubusercontent.com/2159577/136114286-0dfd9eb9-3919-4f1c-b9e7-46e6c3573435.png)  

The ui files were not correctly loading the translations, as the domain had to be set both using `locale.bindtextdomain` and the ui files had to be updated as they were referencing Gourmet still.

I also took care to check other such cases:  
![image](https://user-images.githubusercontent.com/2159577/136114465-e94df609-7e31-45f4-9884-3e00ada53d1b.png)
