### ISSUE TITLE
.desktop and .svg files aren't installed

### ISSUE THREAD

**Issue by marillat** [GourmandRecipeManager/gourmand#83]
When doing a new Debian package I've noticed that desktop file isn't installed.
io.github.GourmandRecipeManager.Gourmand.desktop should be installed in /usr/share/applications

Icons can be installed in different sizes as explained here :
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#install_icons

But only one icon in /usr/share/icons/hicolor/48x48/apps is also sufficient.

**Comment by cydanil** [comment]
Hi @marillat 
I'm not sure exactly what steps I should undertake to make these files available.  
It seems to me it's up to the deb file to have the correct structure, rather than pip having to do this.  

To be fair, I'm not too familiar with this. Could you point me to a project that does it correctly?

**Comment by marillat** [comment]
Well when you install gourmand with the setup.py the desktop and svg should be installed as other files
See https://github.com/GourmandRecipeManager/gourmand/pull/117
